### ISSUE TITLE
Test fails after clean clone run

### ISSUE THREAD

**Issue by DavidGamba** [jdowning/puppet-awscli#58]
Reproduction steps:

1. `/home/david/.gem/ruby/2.3.0/bin/bundle install --path vendor/bundle`

2. `/home/david/.gem/ruby/2.3.0/bin/bundle exec rake spec` :
```
/home/david/.gem/ruby/2.3.0/bin/bundle exec rake spec 
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/defaults.rb:488: warning: key :queue_type is duplicated and overwritten on line 489
rake aborted!
NameError: uninitialized constant Syck
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/require_vendored.rb:4:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor.rb:40:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor.rb:40:in `require_libs'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet/vendor.rb:53:in `load_vendored'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet.rb:172:in `<module:Puppet>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppet-3.7.5/lib/puppet.rb:29:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata-json-lint/semantic_puppet_loader.rb:21:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata-json-lint/semantic_puppet_loader.rb:21:in `try_load_puppet'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata-json-lint/semantic_puppet_loader.rb:5:in `try_load'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata_json_lint.rb:6:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata-json-lint/rake_task.rb:3:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/metadata-json-lint-2.1.0/lib/metadata-json-lint/rake_task.rb:3:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppetlabs_spec_helper-2.6.2/lib/puppetlabs_spec_helper/rake_tasks.rb:11:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/puppetlabs_spec_helper-2.6.2/lib/puppetlabs_spec_helper/rake_tasks.rb:11:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/Rakefile:2:in `require'
/home/david/code/puppet-r10k/modules/puppet-awscli/Rakefile:2:in `<top (required)>'
/home/david/code/puppet-r10k/modules/puppet-awscli/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

Happens with both `master` and tag `2.0.0`.

Thanks!

**Comment by jdowning** [comment]
Fixed in #63

Use `pdk test unit` to test locally
